### ISSUE TITLE
[Peer Review] Code Review of "Investigation of Pharmacological Mechanism of Natural Product Using Pathway Fingerprints Similarity Based on “Drug-Target-Pathway” Heterogenous Network"

### ISSUE THREAD

**Issue by cthoyt** [huihui1126/drugSim-pathway#14]
Hi, I have been asked to review your paper "Investigation of Pharmacological Mechanism of Natural Product Using Pathway Fingerprints Similarity Based on “Drug-Target-Pathway” Heterogenous Network" submitted to the *Journal of Cheminformatics*.

Since this paper is about computational analysis, I will provide a detailed code review and assessment of the reproducibility of the work. This can serve as a table of contents for my feedback on 1) the code that was available at the time of review and 2) things that are missing from this repository that I need to make a full review. My feedback on the scientific content of the manuscript and the manuscript will be sent through the manuscript review system, along with a note to the editor that the following points (unless otherwise noted) should be addressed.

### Missing Assets

- [x] #3 Missing assets to run `PathSim.py`
- [x] #4 Results of PathSim.py are missing
- [x] #7 Missing `hclu.r`
- [x] #8 Data required to run extracRelation.pl are missing
- [x] #11 Missing `goa_human.gaf`

### Provenance for Assets

The following assets are included in the repository without explanation as to how they were generated. Each issue requests more information about how they were generated, including to add the code that did it to this repository

- [x] #12 `combine_score.txt`
- [x] #13  `inflammationresponse.txt`

### Installation

- [x] #1 List Python requirements for PathSim.py
- [x] #6 List perl requirements for extracRelation.pl
- [x] #7 After adding `hclu.r`, there need to be instructions on what version of R to use, how to install requirements, and how to run this script

### General Organization

- [x] #5 Use better file extensions
- [x] #10 Improve README

## Scientific issues

- [x] #9 Alternative analysis to `kegg`
